# This is the default configuration for importing questions as basic Anki cards (Front/Back).
# If you want to use a custom multiple-choice card model, please refer to the README.md for instructions.

card_model: Basic
fields:
  question: Front
  correct_answer: Back
  incorrect_answers: []
  explanation: ''
questions_file: questions.md
